In [24]:
import pandas as pd
import re

from datasets import load_dataset
from sklearn.model_selection import train_test_split

In [25]:
dataset = load_dataset(
    "salehalmansour/english-to-arabic-translate"
)

df = dataset["train"].to_pandas()

print("Columns in dataset:", df.columns.tolist())
print("Dataset shape:", df.shape)

df.head()

Repo card metadata block was not found. Setting CardData to empty.

Columns in dataset: ['en', 'ar']
Dataset shape: (1325899, 2)

                       en                   ar
0                and this               و هذه؟
1               it was um           ...لقد كان
2  what is she doing here  ما الذي تفعله هناك؟
3          i dont like it           لا أحب ذلك
4    did you get the part    هل حصلت على جزء ?

In [27]:
df = df.dropna(subset=["en", "ar"])

print("After removing nulls:", df.shape)

After removing nulls: (1325887, 2)

In [28]:
def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()

    text = re.sub(r'[^\w\s]', '', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()


def normalize_arabic(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ة", "ه", text)

    return text

In [29]:
df["en"] = df["en"].apply(clean_text)

df["ar"] = df["ar"].apply(
    lambda x: normalize_arabic(clean_text(x))
)

df.head()

                       en                  ar
0                and this               و هذه
1               it was um             لقد كان
2  what is she doing here  ما الذي تفعله هناك
3          i dont like it          لا احب ذلك
4    did you get the part     هل حصلت علي جزء

In [34]:
df = df.sample(
    n=200000,
    random_state=42
)

print("Sampled dataset size:", df.shape)

Sampled dataset size: (200000, 2)

In [35]:
train, temp = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

val, test = train_test_split(
    temp,
    test_size=0.5,
    random_state=42
)

print("Train size:", len(train))
print("Validation size:", len(val))
print("Test size:", len(test))

Train size: 160000
Validation size: 20000
Test size: 20000

In [37]:
import os

os.makedirs(
    "data/processed",
    exist_ok=True
)

train.to_csv(
    "data/processed/train.csv",
    index=False
)

val.to_csv(
    "data/processed/val.csv",
    index=False
)

test.to_csv(
    "data/processed/test.csv",
    index=False
)

print("Dataset processed successfully!")

Dataset processed successfully!

In [38]:
print("Final dataset summary:")
print("Total sampled:", len(df))
print("Train:", len(train))
print("Validation:", len(val))
print("Test:", len(test))

Final dataset summary:
Total sampled: 200000
Train: 160000
Validation: 20000
Test: 20000